FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG VITE_HUAWEI_SIGNAL_API
ARG VITE_OLT_SSH_API
ARG VITE_DIAGNOSTICO_API_BASE
ARG VITE_API_BASE_URL
ARG VITE_DIAGNO_URL
ENV VITE_HUAWEI_SIGNAL_API=$VITE_HUAWEI_SIGNAL_API
ENV VITE_OLT_SSH_API=$VITE_OLT_SSH_API
ENV VITE_DIAGNOSTICO_API_BASE=$VITE_DIAGNOSTICO_API_BASE
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_DIAGNO_URL=$VITE_DIAGNO_URL
RUN NODE_OPTIONS="--max-old-space-size=2048" npm run build

FROM node:22-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
