create table if not exists public.historial_appsheet_sync_state (
  source_key text primary key,
  target_table text,
  row_count integer not null default 0,
  synced_at timestamptz not null default now(),
  note text
);

create index if not exists idx_historial_appsheet_sync_state_synced_at
  on public.historial_appsheet_sync_state (synced_at desc);

create table if not exists public.historial_appsheet_extracto (
  id bigint generated by default as identity primary key,
  sheet_row_num integer not null,
  extracto_id text,
  fecha text,
  tipo text,
  responsable text,
  source_sheet text default 'EXTRACTO',
  payload jsonb,
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_historial_appsheet_extracto_sheet_row_num
  on public.historial_appsheet_extracto (sheet_row_num);

create index if not exists idx_historial_appsheet_extracto_id
  on public.historial_appsheet_extracto (extracto_id);

create index if not exists idx_historial_appsheet_extracto_updated_at
  on public.historial_appsheet_extracto (updated_at desc);

create table if not exists public.historial_appsheet_movimientos (
  id bigint generated by default as identity primary key,
  sheet_row_num integer not null,
  id_movimiento text,
  id_detalle text,
  codigo_onu text,
  producto text,
  tecnico text,
  cantidad numeric(12,2),
  precio_unitario numeric(12,2),
  costo_material numeric(12,2),
  source_sheet text default 'DetalleMovimiento',
  payload jsonb,
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_historial_appsheet_movimientos_sheet_row_num
  on public.historial_appsheet_movimientos (sheet_row_num);

create index if not exists idx_historial_appsheet_movimientos_id_mov
  on public.historial_appsheet_movimientos (id_movimiento);

create index if not exists idx_historial_appsheet_movimientos_codigo_onu
  on public.historial_appsheet_movimientos (codigo_onu);

create index if not exists idx_historial_appsheet_movimientos_updated_at
  on public.historial_appsheet_movimientos (updated_at desc);

create table if not exists public.historial_appsheet_ordenes_basedata (
  id bigint generated by default as identity primary key,
  sheet_row_num integer not null,
  codigo text,
  fecha text,
  nodo text,
  empresa text,
  source_sheet text default 'BaseData',
  payload jsonb,
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_historial_appsheet_basedata_sheet_row_num
  on public.historial_appsheet_ordenes_basedata (sheet_row_num);

create index if not exists idx_historial_appsheet_basedata_codigo
  on public.historial_appsheet_ordenes_basedata (codigo);

create index if not exists idx_historial_appsheet_basedata_nodo
  on public.historial_appsheet_ordenes_basedata (nodo);

create index if not exists idx_historial_appsheet_basedata_updated_at
  on public.historial_appsheet_ordenes_basedata (updated_at desc);
