-- Historial de ONUsRegistradas desde Google Sheet/AppSheet
create table if not exists public.historial_appsheet_onus (
  id bigint generated by default as identity primary key,
  id_onu text not null,
  id_register text,
  producto text,
  estado text,
  tecnico_asignado_codigo text,
  fecha_registro text,
  foto_etiqueta_raw text,
  foto_etiqueta_url text,
  usuario_pppoe text,
  nodo text,
  nombre_cliente text,
  dni text,
  liquidado_por_codigo text,
  fecha_liquidacion text,
  fecha_asignacion text,
  empresa text,
  foto02_raw text,
  foto02_url text,
  source_sheet text default 'ONUsRegistradas',
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_historial_appsheet_onus_id_onu
  on public.historial_appsheet_onus (id_onu);

create index if not exists idx_historial_appsheet_onus_updated_at
  on public.historial_appsheet_onus (updated_at desc);

create index if not exists idx_historial_appsheet_onus_nodo
  on public.historial_appsheet_onus (nodo);

create index if not exists idx_historial_appsheet_onus_dni
  on public.historial_appsheet_onus (dni);
