create table if not exists public.historial_appsheet_liquidaciones (
  id bigint generated by default as identity primary key,
  codigo text not null,
  orden text,
  orden_id text,
  actuacion text,
  tipo_actuacion text,
  fecha text,
  cliente text,
  nombre text,
  dni text,
  direccion text,
  celular text,
  ubicacion_gps text,
  user_hotspot text,
  parametro text,
  metodo_pago text,
  captura_pago_url text,
  foto_fachada_url text,
  observacion text,
  foto_opcional_url text,
  drop_monto_plan text,
  conector_fibra_velocidad text,
  cable_rg6_codigo_etiqueta text,
  personal_tecnico text,
  foto_onu_url text,
  user_pppoe text,
  photo_caj_url text,
  photo_onu_url text,
  autor text,
  empresa text,
  nodo text,
  tecnico text,
  resultado text,
  monto numeric(12,2) default 0,
  sn_onu text,
  estado text,
  source_sheet text default 'Liquidaciones',
  payload jsonb,
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_historial_appsheet_liquidaciones_codigo
  on public.historial_appsheet_liquidaciones (codigo);

create index if not exists idx_historial_appsheet_liquidaciones_updated_at
  on public.historial_appsheet_liquidaciones (updated_at desc);

create index if not exists idx_historial_appsheet_liquidaciones_dni
  on public.historial_appsheet_liquidaciones (dni);

create index if not exists idx_historial_appsheet_liquidaciones_nodo
  on public.historial_appsheet_liquidaciones (nodo);

create index if not exists idx_historial_appsheet_liquidaciones_tecnico
  on public.historial_appsheet_liquidaciones (tecnico);

create table if not exists public.historial_appsheet_detalle_liquidacion (
  id bigint generated by default as identity primary key,
  detalle_key text not null,
  id_liqui text,
  orden_id text,
  liquidacion_codigo text,
  codigo_material text,
  codigo_onu text,
  material text,
  unidad text,
  cantidad numeric(12,2) default 0,
  precio_unitario numeric(12,4) default 0,
  subtotal numeric(12,2) default 0,
  tecnico text,
  cliente text,
  dni text,
  nodo text,
  fecha text,
  observacion text,
  source_sheet text default 'DetalleLiquidacion',
  payload jsonb,
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_historial_appsheet_detalle_liquidacion_key
  on public.historial_appsheet_detalle_liquidacion (detalle_key);

create index if not exists idx_historial_appsheet_det_liq_updated_at
  on public.historial_appsheet_detalle_liquidacion (updated_at desc);

create index if not exists idx_historial_appsheet_det_liq_codigo
  on public.historial_appsheet_detalle_liquidacion (liquidacion_codigo);

create index if not exists idx_historial_appsheet_det_liq_codigo_onu
  on public.historial_appsheet_detalle_liquidacion (codigo_onu);

create index if not exists idx_historial_appsheet_det_liq_nodo
  on public.historial_appsheet_detalle_liquidacion (nodo);

create table if not exists public.historial_appsheet_articulos (
  id bigint generated by default as identity primary key,
  id_articulo text not null,
  codigo text,
  nombre text,
  info text,
  marca text,
  modelo text,
  precio_unitario numeric(12,2) default 0,
  foto_art_raw text,
  foto_art_url text,
  source_sheet text default 'ARTICULOS',
  payload jsonb,
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_historial_appsheet_articulos_id_articulo
  on public.historial_appsheet_articulos (id_articulo);

create index if not exists idx_historial_appsheet_articulos_codigo
  on public.historial_appsheet_articulos (codigo);

create index if not exists idx_historial_appsheet_articulos_updated_at
  on public.historial_appsheet_articulos (updated_at desc);
